[package]
name = "gossip-glomers"
version = "0.1.0"
edition = "2021"
authors = ["Tomas Drtina <tm.drtina@gmail.com>"]

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
ulid = { version = "1.0.0", features = ["serde"] }
